### ISSUE TITLE
cdo functions

### ISSUE THREAD

**Issue by DamienIrving** [CWSL/cwsl-mas#18]
@ScottWales Jaci Brown has contracted me to work on the CWSLab vistrails plugin for the month of May (i.e. they want we to get some useful packages in there so they can start using it down in Hobart). I was chatting to @taerwin and he mentioned that you have a fork of this repo where you are working on automatically importing all the cdo functions? Is that something you are planning on implementing soon, or do you think the approach we have taken so far of wrapping the cdo commands in shell scripts that check various things (e.g. that the input arguments and time stamps in the output file are correct) is a better approach?

**Comment by ScottWales** [comment]
The idea is to set up a list of CDO functions and import them automatically based on their help text, e.g. given 

```
$ cdo --help ymonsub
NAME
    ymonadd, ymonsub, ymonmul, ymondiv - Multi-year monthly arithmetic

SYNOPSIS
    <operator>  ifile1 ifile2 ofile
```

create operators `ymonadd`, `ymonsub` etc. with two inputs and one output.

I couldn't work out how to create the output dataset though, see #17. If you can work out how to implement `compute()` in [1] then this approach should work, and you could just feed in the helptext from all of the operators to quickly get things going.

[1] https://github.com/ScottWales/cwsl-mas/blob/cdo/cwsl/vt_modules/vt_cdo.py

**Comment by captainceramic** [comment]
This is quite difficult to do because of the way that the plugin is set up, but I'm sure that it would not be impossible.

I started writing a response to your issue and realised it would be better in the wiki, so I have put it up [here](https://github.com/CWSL/cwsl-mas/wiki/Developer-Introduction)

The difficulty in doing this is that the plugin works out how to map inputs to outputs by examining the pattern that you want to write files to. Some `cdo` operators are many-to-one, some are one-to-one, so they need different output patterns to be able to group the files correctly.

I'm sure that this can be done though.

**Comment by ScottWales** [comment]
Are the patterns required for the output `DataSet`? Would it be enough to ensure that the output has the same ordering as the input `DataSet`s?

Alternatively you might use the union of the patterns in the input datasets, with a special marker pattern where there's a conflict, e.g.

```
ymonadd [blue/kangaroo] [green/kangaroo] -> [#MERGED/kangaroo]
```

**Comment by captainceramic** [comment]
As written at the moment a `DataSet` does need a pattern, because it has to link a particular combination of file attributes ('blue' and 'kangaroo' in this case) with a file name. I have experimented with generating this pattern procedurally though - especially for cases when the process is an intermediate step in a workflow.

Your suggestion of using the union of the inputs as an output pattern is worth looking at. This approach could be a good fallback if an output pattern isn't provided in the `ProcessUnit` constructor.

In this case of `ymonadd` there are two conceptually different `DataSet` objects that are being used as input (the timeseries file and and the single timestep file). Often `cdo` operators perform reduction operations on a single `DataSet`, such as `cdo mergetime` or `cdo ensmean`. In this case the plugin uses a combination of the output pattern and any extra information given in the `ProcessUnit` constructor to determine which attributes to perform a reduction over. If you have a look at the `ProcessUnit` tests you'll see this can be quite a complex thing to do! There could certainly be some API simplifications.

**Comment by DamienIrving** [comment]
Given that a `DataSet` does need a pattern at the moment and that I need to get some basic functionality into the plugin for the oceanographers in Hobart by the end of the month (almost all of which can be done with cdo), I'm thinking we should revisit this idea of automatically incorporating cdo commands at a later date. For now, I'm thinking I'll take the approach of simply grouping like-cdo commands into [`vt_modules`](https://github.com/CWSL/cwsl-mas/tree/master/cwsl/vt_modules) wrappers (by "like" I mean commands that take the same inputs and map to the same constraints). 

For instance, `fldmean`, `fldmax`, `fldsum` etc all take the same input (one input file and one output file) and map to the same constraint/s (i.e. they all collapse the spatial dimension of the data), so I'd group them all in a wrapper called `vt_aggregate_spatial.py`. I could add an extra layer of wrapping and include a shell script (`aggregate_spatial.sh`) to the [ctools repo](https://github.com/CWSL/cwsl-ctools) if I felt that some additional nco or cdo commands were needed to clean up undesirable aspects of the cdo generated metadata (e.g. sometimes it's desirable to edit the default time axis generated during temporal aggregation). 

Does that sound like a reasonable approach for the purposes for getting the Hobart group going? I'm thinking it would be nice to solve #21 before embarking on writing these wrappers, otherwise all the output patterns would need to be updated retrospectively (perhaps #21 is something I could work on solving during the month of May?).

**Comment by captainceramic** [comment]
I think that sounds like a good approach. Adding a a good quality, reliable set of processing scripts to ctools gives users a reason to use the lab VMs outside of the the VisTrails system, and a more familiar entry point.

I vote that we close this issue for now, but revisit it in the future.

@ScottWales idea of procedurally generating modules from text could be generalized to allow users to create modules by writing module descriptions (perhaps in JSON?).

**Comment by DamienIrving** [comment]
This seems like a difficult issue to solve and most of the main cdo functions have now been implemented anyway, so we have decided to park it at the moment.
